import {DichVu} from '../model/DichVu';
export const dichvuDao: DichVu[] = [
  {
    idDV: 1,
    tenDV: 'Room',
    dienTich: 123,
    soTang: 12,
    soNguoiToiDa: '10',
    chiPhiThue: '1230000',
    kieuThue: 'ngày',
    trangThai: 'còn dịch vụ',
  },
  {
    idDV: 2,
    tenDV: 'Villa ',
    dienTich: 343,
    soTang: 2,
    soNguoiToiDa: '12',
    chiPhiThue: '1230000',
    kieuThue: 'tháng',
    trangThai: 'Hết dịch vụ',
  },
  {
    idDV: 3,
    tenDV: 'House',
    dienTich: 123,
    soTang: 12,
    soNguoiToiDa: '10',
    chiPhiThue: '1230000',
    kieuThue: 'ngày',
    trangThai: 'còn dịch vụ',
  },
  {
    idDV: 4,
    tenDV: 'Tắm Biển',
    dienTich: 123,
    soTang: 12,
    soNguoiToiDa: '10',
    chiPhiThue: '1230000',
    kieuThue: 'ngày',
    trangThai: 'còn dịch vụ',
  },
];
